name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Clean build artifacts
        run: |
          # Remove any existing dist files
          rm -rf dist/ build/ *.egg-info/
          # Also clean any potential cached files
          find . -name "*.pyc" -delete
          find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Verify build version
        run: |
          echo "Built files:"
          ls -la dist/
          # This should show 0.1.1 files, not 0.1.0
          if ls dist/*0.1.0* 2>/dev/null; then
            echo "ERROR: Still building old version 0.1.0!"
            exit 1
          fi

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Verify downloaded artifacts
        run: |
          echo "Files to be published:"
          ls -la dist/
          # This should show 0.1.1 files

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist/
